### ISSUE TITLE
Broken documentation

### ISSUE THREAD

**Issue by moosebuild** [idaholab/malamute#24]
In [GitLab](https://hpcgitlab.hpc.inl.gov/idaholab/malamute/-/issues/24) by @cticenhour on Dec 14, 2021, 16:08

This issue is a reproduction of the archived freya#28 for SQA purposes. Please refer to that issue for any extended discussion that may exist beyond this description. 

## Bug Description
Freya docs are broken due to a duplicate image conflict resulting from the development of the electromagnetics module:

```
RENDER ERROR: Multiple pages with a name that ends with 'two_block.png' were found:
  media/two_block.png
  large_media/electromagnetics/two_block.png
/opt/civet/build_1/freya/doc/content/verification/thermal_contact_verification.md:339
   ┌───────────────────────────────────────────────────────────────────────────────────────────────┐
339│                                                                                               │
340│                                                                                               │
   └───────────────────────────────────────────────────────────────────────────────────────────────┘
Traceback (most recent call last):
  File "/opt/civet/build_1/freya/moose/python/MooseDocs/base/renderers.py", line 77, in render
    el = func(parent, token, page) if func else parent
  File "/opt/civet/build_1/freya/moose/python/MooseDocs/extensions/media.py", line 151, in createMaterialize
    tag = self.createHTML(parent, token, page)
  File "/opt/civet/build_1/freya/moose/python/MooseDocs/extensions/media.py", line 141, in createHTML
    node = self.translator.findPage(src)
  File "/opt/civet/build_1/freya/moose/python/MooseDocs/base/Translator.py", line 223, in findPage
    raise exceptions.MooseDocsException(msg)
MooseDocs.common.exceptions.MooseDocsException: Multiple pages with a name that ends with 'two_block.png' were found:
  media/two_block.png
  large_media/electromagnetics/two_block.png
```

## Steps to Reproduce
Try to build Freya docs with current MOOSE submodule. 

## Impact
Docs will not build correctly until fixed.

**Comment by moosebuild** [comment]
In GitLab by @cticenhour on Jul 14, 2022, 16:13

mentioned in commit 0144301ffd5e0b31556d79b1184ad8153e9887b5

**Comment by moosebuild** [comment]
In GitLab by @sapitts on Jul 14, 2022, 16:13

mentioned in commit 2908ec25382b0fa8fe71292927123d2dcdec51f1
